CREATE DATABASE MedicalHelp;
USE MedicalHelp;



CREATE TABLE ROL
(
	ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_ROL VARCHAR(50) DEFAULT 'USUARIO' NULL
);

CREATE TABLE TIPODEDOCUMENTO
(
	ID_TIPODEDOCUMENTO INT PRIMARY KEY AUTO_INCREMENT,
	TIPODEDOCUMENTO INT NOT NULL
);

CREATE TABLE USUARIO
(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_TIPODEDOCUMENTO INT NOT NULL,
	ID_ROL INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(50) NOT NULL,
    NUMERODEDOCUMENTO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
    FECHADENACIMIENTO DATE NOT NULL,
    CONSTRAINT USUARIO_TIPODEDOCUMENTO FOREIGN KEY (ID_TIPODEDOCUMENTO) REFERENCES TIPODEDOCUMENTO (ID_TIPODEDOCUMENTO),
    CONSTRAINT USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE REGISTROMEDICO
(
	ID_REGISTROMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR(1000) NOT NULL,
    OBSERVACION VARCHAR(1000) NOT NULL
);

CREATE TABLE CITA
(
	ID_CITA INT PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_REGISTROMEDICO INT NOT NULL,
	FECHA DATE NOT NULL,
    DIRECCION VARCHAR(1000) NOT NULL,
    CONSTRAINT CITA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CITA_REGISTROMEDICO FOREIGN KEY (ID_REGISTROMEDICO) REFERENCES REGISTROMEDICO (ID_REGISTROMEDICO)
);
